# Configuración de la Base de datos
spring.datasource.url=jdbc:mysql://localhost:3307/visitasvirtuales?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
#jdbc:mysql://localhost:3307/visitasvirtuales?useSSL=false&serverTimezone=UTC
# Configuración de JPA/Hibernate
# 'Update' hace que Hibernate cree o actualice las tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Definición de los roles como un diccionario
app.seguridad.roles[0]=alumno
app.seguridad.roles[1]=profesor
app.seguridad.roles[2]=administrador
app.seguridad.roles[3]=invitado

# Implementación de JWT
# Clave secreta para firmar el JWT
jwt.secret=VGhpc0lzQVNlY3JldEtleUZvclRoZVNlY3VyaXR5Q2hlY2s=
# Tiempo de vida del JWT (milisegundos) 86400000ms = 24 horas
jwt.expiration.ms=86400000