services:
  api_service:
    build: .
    container_name: vv-api
    image: visitas-virtuales-api:0.1.0
    ports:
      - '8000:8000'
    restart: always
    environment:
      - APP_STAGE=prod
    env_file:
      - .env.prod
    depends_on:
      - postgres_service
    networks:
      - vv-network

  postgres_service:
    image: postgres:16
    container_name: vv-postgres
    restart: always
    env_file:
      - .env.prod
    environment:
      TZ: Europe/Madrid
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
    networks:
      - vv-network

  minio_service:
    image: minio/minio
    container_name: vv-minio
    env_file:
      - .env.prod
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: bucket1
    networks:
      - vv-network
    ports:
      - '9000:9000'
      - '9001:9001' # Consola web de MinIO
    command: server /data --console-address ":9001"
    volumes:
      - miniodata-prod:/data

networks:
  vv-network:
    driver: bridge

volumes:
  pgdata-prod:
  miniodata-prod:
